blueprint:
  name: Zigbee2MQTT Sensors Offline Notification
  description: "This blueprint monitors the online status of Zigbee2MQTT sensors connected to your Home Assistant. If any sensor goes offline, the automation sends a notification to inform you. You can monitor multiple sensors and adjust the notification interval."
  domain: automation
  input:
    trigger_sensor:
      name: Trigger Sensor
      description: "The sensor to monitor for offline status."
      selector:
        entity:
          domain: sensor
    notification_service:
      name: Notification Service
      description: "The service to use for sending notifications."
      selector:
        entity:
          domain: notify
    notify_interval:
      name: Notification Interval
      description: "How often to notify if a sensor is offline."
      default: 60
      selector:
        number:
          min: 1
          max: 1440
          unit_of_measurement: minutes
          mode: slider
          step: 1
    include_sensors:
      name: Sensors to Monitor
      description: "The list of sensors to monitor for offline status."
      selector:
        target:
          entity:
            domain: sensor
          multiple: true
  source_url: "https://github.com/yourusername/zigbee-sensors-offline-notification"
mode: restart
max_exceeded: silent
variables:
  trigger_sensor: !input trigger_sensor
  notification_service: !input notification_service
  notify_interval: !input notify_interval
  include_sensors: !input include_sensors
trigger:
  - platform: state
    entity_id: !input trigger_sensor
    to: 'unavailable'
    for:
      minutes: !input notify_interval
condition: []
action:
  - service: !input notification_service
    data:
      message: "The Zigbee2MQTT sensor {{ trigger.to_state.entity_id }} is offline!"
      title: "Zigbee Sensor Offline"
