blueprint:
  name: Zigbee2MQTT Sensors Offline Notification
  description: |
    # Zigbee2MQTT Sensors Offline Notification\n
    **Version: 1.0**\n
    
    This blueprint monitors the online status of Zigbee2MQTT sensors connected to your Home Assistant.\n
    If any sensor goes offline, the automation sends a notification to inform you.\n
    
    **Features:**\n
    - Monitors the status of selected Zigbee2MQTT sensors.\n
    - Sends notifications at specified intervals to avoid excessive alerts.\n
    - Allows you to add or remove sensors dynamically.\n
    - Supports various notification platforms, including the Home Assistant app, email, or other messaging services.\n
    
    **Automation Process:**\n
    - The automation checks the `availability` attribute of each sensor.\n
    - If a sensor is offline, a notification is sent with the sensor's name.\n
    - Notifications are throttled based on the configured time interval.\n
    
    **Setup Instructions:**\n
    1. Select the Zigbee2MQTT sensors you want to monitor.\n
    2. Choose the notification service (e.g., mobile push, email).\n
    3. Set the interval for notification reminders.\n
    
    **Need help?** Visit the Home Assistant Community for support: [Click Here](https://community.home-assistant.io/)\n
    
    **Required Inputs:**\n
    - *Sensors:* The Zigbee2MQTT sensors to monitor.\n
    - *Notification Service:* The service to use for notifications.\n
    
    ---\n
 domain: automation
  input:
    sensors:
      name: Sensors to Monitor *
      description: Select the Zigbee2MQTT sensors you want to monitor.
      selector:
        entity:
          domain: binary_sensor
          integration: mqtt
          multiple: true
    notify_service:
      name: Notification Service *
      description: Select the notification service to use for alerts.
      selector:
        service: notify
    notification_interval:
      name: Notification Interval
      description: Set the interval (in minutes) for notifications.
      default: 30
      selector:
        number:
          min: 1
          max: 1440
          unit_of_measurement: minutes
          mode: slider

  source_url: https://github.com/<your-username>/home-assistant-blueprints

mode: restart
max_exceeded: silent
variables:
  sensors: !input sensors
  notify_service: !input notify_service
  interval: !input notification_interval

trigger:
  - platform: time_pattern
    minutes: "/{{ interval }}"

condition:
  - condition: template
    value_template: >
      {% set offline_sensors = sensors | select('is_off', states) | list %}
      {{ offline_sensors | length > 0 }}

action:
  - variables:
      offline_sensors: >
        {{ sensors | select('is_off', states) | map(attribute='name') | list | join(', ') }}
  - service: !input notify_service
    data:
      message: >
        The following Zigbee2MQTT sensors are offline: {{ offline_sensors }}
